export const INQUIRY_REQUEST = "INQUIRY_REQUEST"
export const INQUIRY_SUCCESS = "INQUIRY_SUCCESS"
export const INQUIRY_FAIL = "INQUIRY_FAIL"

export const LIST_INQUIRY_REQUEST = "LIST_INQUIRY_REQUEST"
export const LIST_INQUIRY_SUCCESS = "LIST_INQUIRY_SUCCESS"
export const LIST_INQUIRY_FAIL = "LIST_INQUIRY_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"