export const HOME_DETAILS_REQUEST = "HOME_DETAILS_REQUEST"
export const HOME_DETAILS_SUCCESS = "HOME_DETAILS_SUCCESS"
export const HOME_DETAILS_FAIL = "HOME_DETAILS_FAIL"

export const UPDATE_HOME_REQUEST = "UPDATE_HOME_REQUEST"
export const UPDATE_HOME_SUCCESS = "UPDATE_HOME_SUCCESS"
export const UPDATE_HOME_FAIL = "UPDATE_HOME_FAIL"
export const UPDATE_HOME_RESET = "UPDATE_HOME_RESET"

export const CLEAR_ERRORS = "CLEAR_ERRORS"