export const HOME_DETAILS_REQUEST = "HOME_DETAILS_REQUEST"
export const HOME_DETAILS_SUCCESS = "HOME_DETAILS_SUCCESS"
export const HOME_DETAILS_FAIL = "HOME_DETAILS_FAIL"

export const UPDATE_HOME_REQUEST = "UPDATE_HOME_REQUEST"
export const UPDATE_HOME_SUCCESS = "UPDATE_HOME_SUCCESS"
export const UPDATE_HOME_FAIL = "UPDATE_HOME_FAIL"
export const UPDATE_HOME_RESET = "UPDATE_HOME_RESET"

export const ABOUT_DETAILS_REQUEST = "ABOUT_DETAILS_REQUEST"
export const ABOUT_DETAILS_SUCCESS = "ABOUT_DETAILS_SUCCESS"
export const ABOUT_DETAILS_FAIL = "ABOUT_DETAILS_FAIL"

export const ALL_ABOUT_DETAILS_REQUEST = "ALL_ABOUT_DETAILS_REQUEST"
export const ALL_ABOUT_DETAILS_SUCCESS = "ALL_ABOUT_DETAILS_SUCCESS"
export const ALL_ABOUT_DETAILS_FAIL = "ALL_ABOUT_DETAILS_FAIL"

export const UPDATE_ABOUT_REQUEST = "UPDATE_ABOUT_REQUEST"
export const UPDATE_ABOUT_SUCCESS = "UPDATE_ABOUT_SUCCESS"
export const UPDATE_ABOUT_FAIL = "UPDATE_ABOUT_FAIL"
export const UPDATE_ABOUT_RESET = "UPDATE_ABOUT_RESET"

export const FOOTER_DETAILS_REQUEST = "FOOTER_DETAILS_REQUEST"
export const FOOTER_DETAILS_SUCCESS = "FOOTER_DETAILS_SUCCESS"
export const FOOTER_DETAILS_FAIL = "FOOTER_DETAILS_FAIL"

export const UPDATE_FOOTER_REQUEST = "UPDATE_FOOTER_REQUEST"
export const UPDATE_FOOTER_SUCCESS = "UPDATE_FOOTER_SUCCESS"
export const UPDATE_FOOTER_FAIL = "UPDATE_FOOTER_FAIL"
export const UPDATE_FOOTER_RESET = "UPDATE_FOOTER_RESET"

export const CLEAR_ERRORS = "CLEAR_ERRORS"