export const GET_HOME_REQUEST = "GET_HOME_REQUEST"
export const GET_HOME_SUCCESS = "GET_HOME_SUCCESS"
export const GET_HOME_FAIL = "GET_HOME_FAIL"

export const UPDATE_HOME_REQUEST = "UPDATE_HOME_REQUEST"
export const UPDATE_HOME_SUCCESS = "UPDATE_HOME_SUCCESS"
export const UPDATE_HOME_FAIL = "UPDATE_HOME_FAIL"
export const UPDATE_HOME_RESET = "UPDATE_HOME_RESET"

export const CLEAR_ERRORS = "CLEAR_ERRORS"